apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: ops-ingress-properties
    literals:
      - FOO=foo
      - BAR=bar$(foo)
      - BAT=tab

vars:
  - name: FOO
    objref: { kind: ConfigMap, name: ops-ingress-properties, apiVersion: v1 }
    fieldref: { fieldpath: data.FOO }
  - name: BAR
    objref: { kind: ConfigMap, name: ops-ingress-properties, apiVersion: v1 }
    fieldref: { fieldpath: data.BAR }
