apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: ops-ingress-properties
    literals:
      - FOO=foo
      - BAR=bar$(foo)
      - BAT=tab
  - name: dctest1
    literals:
      - A1=A1
      - B1=B1
      - C1=C1
      - D1=D1

vars:
  - name: FOO
    objref: { kind: ConfigMap, name: ops-ingress-properties, apiVersion: v1 }
    fieldref: { fieldpath: data.FOO }
  - name: BAR
    objref: { kind: ConfigMap, name: ops-ingress-properties, apiVersion: v1 }
    fieldref: { fieldpath: data.BAR }
