apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#########################
## resources
#########################
resources:
  - ../../../base/ui/

patchesStrategicMerge:
  - patches/deployment-env.yaml

#########################
## Image Tags
#########################
#images:
#  - name:
#    newTag:
