apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redis-commander-localhost
spec:
  ingressClassName: nginx
  rules:
    - host: commander.test.local
      http:
        paths:
          - path: "/"
            backend:
              serviceName: redis-commander
              servicePort: 80
