---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis
  template:
    metadata:
      labels:
        name: redis
    spec:
      containers:
        - name: redis
          image: redis:7
          ports:
            - name: redis
              containerPort: 6379
        - name: redis-commander-2
          image: ghcr.io/joeferner/redis-commander:latest
          ports:
            - name: http-odd
              containerPort: 8081
          env:
            - name: REDIS_HOSTS
              value: redis
      nodeSelector:
        beta.kubernetes.io/os: linux
