apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx-img
          name: nginx
          ports:
            - containerPort: 80
          env:
            - name: FOO
              value: $(FOO)
            - name: BAR
              value: $(BAR)
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
