apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


#########################
## resources
#########################
resources:
  - deployment.yaml
  - svc.yaml
images:
  ## echo-api Image
  - name: nginx-img
    newName: nginx
    newTag: '1.25'
