apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress-ui-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  defaultBackend:
    service:
      name: wordpress-ui
      port:
        number: 80
