---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-db
  labels:
    name: wordpress-db
spec:
  ports:
    # the port that this service should serve on
  - port: 3306
    targetPort: 3306
  selector:
    name: wordpress-db
