apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress-ui-ingress
spec:
  rules:
  - host: wordpress-ui.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wordpress-ui
            port:
              number: 80
  ingressClassName: nginx
