apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


#########################
## resources
#########################
resources:
  - wordpress-ui-deployment.yaml
  - wordpress-ui-svc.yaml
