apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#########################
## resources
#########################
resources:
  - base/ui-deployment.yaml
  - base/ui-ingress.yaml
  - base/ui-svc.yaml
  - base/phpmyadmin-deployment.yaml
  - base/phpmyadmin-ingress.yaml
  - base/phpmyadmin-svc.yaml
  - base/db-deployment.yaml
  - base/db-svc.yaml
