apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#########################
## resources
#########################
resources:
  - base/wordpress-ui-deployment.yaml
  - base/wordpress-ui-svc.yaml
