---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-db
  labels:
    name: wordpress-db
spec:
  replicas: 1
  selector:
    matchLabels:
      name: wordpress-db
  template:
    metadata:
      labels:
        name: wordpress-db
    spec:
      containers:
      - name: wordpress-db
        image: bitnami/mysql:5.7
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: fake_password
          - name: MYSQL_DATABASE
            value: wordpress
          - name: MYSQL_USER
            value: wordpress-usr
          - name: MYSQL_PASSWORD
            value: wordpress-pwd
        ports:
        - name: mysql
          containerPort: 3306
        livenessProbe:
          exec:
            command:
              - "exit"
              - "$(test $(date +%M) -eq 01 && echo 1 || echo 0)"
        startupProbe:
          exec:
            command:
              - "cat"
              - "/opt/bitnami/mysql/tmp/mysqld.pid"
          failureThreshold: 30
          periodSeconds: 10
      nodeSelector:
        beta.kubernetes.io/os: linux
