apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: wordpress-ui
  template:
    metadata:
      labels:
        app: wordpress-ui
    spec:
      containers:
        - image: wordpress-ui-img
          name: wordpress-ui
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: wordpress-db
            - name: WORDPRESS_DB_USER
              value: wordpress-usr
            - name: WORDPRESS_DB_PASSWORD
              value: wordpress-pwd
            - name: WORDPRESS_DB_NAME
              value: wordpress
