apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


#########################
## resources
#########################
resources:
  - deployment.yaml
  - svc.yaml
images:
  ## echo-api Image
  - name: wordpress-ui-img
    newName: docker.io/library/wordpress
    newTag: '6.2.2'

configMapGenerator:
  - name: ops-ingress-properties
    envs: [environment.properties]

vars:
  - name: FOO
    objref: { kind: ConfigMap, name: ops-ingress-properties, apiVersion: v1 }
    fieldref: { fieldpath: data.FOO }
  - name: BAR
    objref: { kind: ConfigMap, name: ops-ingress-properties, apiVersion: v1 }
    fieldref: { fieldpath: data.BAR }
