apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#########################
## resources
#########################
resources:
  - base/demo-deployment.yaml
  - base/demo-svc.yaml
  - base/demo-ingress.yaml
