apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#########################
## resources
#########################
resources:
  - base/httpd-deployment.yaml
  - base/httpd-svc.yaml
  - base/httpd-ingress.yaml
