apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#########################
## resources
#########################
resources:
  - ../../base/db/
  - ../../base/ui/
  - ../../base/phpmyadmin/


#########################
## Image Tags
#########################
#images:
#  - name:
#    newTag:
