apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#########################
## resources
#########################
resources:
  - ../../base/db/
  - ui/
  - ../../base/phpmyadmin/

configMapGenerator:
  - name: ops-ingress-properties
    envs: [environment.properties]
    behavior: replace
