apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#########################
## resources
#########################
resources:
  - ../../base/db/
  - ui/
  - ../../base/phpmyadmin/

configMapGenerator:
  - name: ops-ingress-properties2
    envs: [environment.properties]

vars:
  - name: FOO
    objref: { kind: ConfigMap, name: ops-ingress-properties2, apiVersion: v1 }
    fieldref: { fieldpath: data.FOO }
