apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#########################
## resources
#########################
resources:
  - ../../base/db/
#  - ui/
#  - ../../base/phpmyadmin/
#  - ../../base/nginx/
  - ../../base/_global/

configMapGenerator:
  - name: ops-ingress-properties
    behavior: replace
    literals:
      - FOO=foo
      - BAR=bar$(foo)
      - BAT=tab
vars:
  - name: BAT
    objref: { kind: ConfigMap, name: ops-ingress-properties, apiVersion: v1 }
    fieldref: { fieldpath: data.BAT }
