apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#########################
## resources
#########################
resources:
  - ../../base/db/
  - ui/
  - ../../base/phpmyadmin/
  - ../../base/nginx/
  - ../../base/_global/

patches:
  - path: nginx/patch-ingress.yaml

configMapGenerator:
  - name: ops-ingress-properties
    behavior: replace
    literals:
      - FOO=foo
      - BAR=bar$(foo)
      - BAT=tab
      - UI_URL=foo.ui.nowhere.com
vars:
  - name: BAT
    objref: { kind: ConfigMap, name: ops-ingress-properties, apiVersion: v1 }
    fieldref: { fieldpath: data.BAT }
