apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#########################
## namePrefix
#########################

namespace: tn-msp-echo-ci-auto

#########################
## resources
#########################
resources:
  - ../../base/


#########################
## Image Tags
#########################
#images:
#  - name:
#    newTag:
