apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#########################
## resources
#########################
resources:
  - base/commander-deployment.yaml
  - base/commander-svc.yaml
  - base/redis-deployment.yaml
  - base/redis-svc.yaml
